// Generated by delombok at Mon Aug 29 15:32:21 MSK 2016
/* 
 * (c) 2008- RANDI2 Core Development Team
 * 
 * This file is part of RANDI2.
 * 
 * RANDI2 is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 * 
 * RANDI2 is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * RANDI2. If not, see <http://www.gnu.org/licenses/>.
 */
package de.randi2.jsf.supportBeans;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.event.ActionEvent;
import javax.faces.model.SelectItem;
import com.icesoft.faces.component.outputchart.OutputChart;
import com.icesoft.faces.context.effects.Effect;
import com.icesoft.faces.context.effects.Highlight;
import de.randi2.jsf.controllerBeans.TrialHandler;
import de.randi2.services.ChartData;
import de.randi2.services.ChartsService;

/**
 * Backing bean for the charts.
 * @author Lukasz Plotnicki <l.plotnicki@dkfz.de>
 */
@ManagedBean(name = "charts")
@RequestScoped
public class Charts {
	List<SelectItem> chartTypes;
	@ManagedProperty("#{trialHandler}")
	private TrialHandler trialHandler;
	@ManagedProperty("#{chartsService}")
	private ChartsService service;
	private String rChartType = "barclustered";
	private Map<String, String> clickedValues;
	private Map<String, Effect> effects;

	public Charts() {
		chartTypes = new ArrayList<SelectItem>();
		chartTypes.add(new SelectItem("barclustered", "Bars (clustered)"));
		chartTypes.add(new SelectItem("line", "Lines"));
		chartTypes.add(new SelectItem("area", "Area"));
		clickedValues = new HashMap<String, String>();
		effects = new HashMap<String, Effect>();
		clickedValues.put("armChart", "not selected");
		Effect e1 = new Highlight("#fda505");
		e1.setFired(true);
		effects.put("armChart", e1);
		clickedValues.put("recruitmentChart", "not selected");
		Effect e2 = new Highlight("#fda505");
		e2.setFired(true);
		effects.put("recruitmentChart", e2);
		clickedValues.put("strataChart", "not selected");
		Effect e3 = new Highlight("#fda505");
		e3.setFired(true);
		effects.put("strataChart", e3);
		clickedValues.put("trialSiteChart", "not selected");
		Effect e4 = new Highlight("#fda505");
		e4.setFired(true);
		effects.put("trialSiteChart", e4);
	}

	/**
	 * Action for the user interaction with the chart.
	 *
	 * @param event
	 * - JSF event
	 */
	public void action(ActionEvent event) {
		if (event.getSource() instanceof OutputChart) {
			OutputChart chart = (OutputChart) event.getSource();
			clickedValues.put(chart.getId(), "not selected");
			if (chart.getClickedImageMapArea().getXAxisLabel() != null) {
				clickedValues.put(chart.getId(), "(" + chart.getClickedImageMapArea().getXAxisLabel() + "  |  " + chart.getClickedImageMapArea().getValue() + ")");
				effects.get(chart.getId()).setFired(false);
			} else {
				chart.getClickedImageMapArea().getValue();
			}
		}
	}

	public ChartData getRChartData() {
		if (trialHandler.getCurrentObject() != null) return service.generateRecruitmentChart(trialHandler.getCurrentObject());
		return null;
	}

	public ChartData getAChartData() {
		if (trialHandler.getCurrentObject() != null) return service.generateArmChart(trialHandler.getCurrentObject());
		return null;
	}

	public ChartData getRTrialSiteChartData() {
		if (trialHandler.getCurrentObject() != null) return service.generateRecruitmentChartTrialSite(trialHandler.getCurrentObject());
		return null;
	}

	public ChartData getRFactorsChartData() {
		if (trialHandler.getCurrentObject() != null) return service.generateRecruitmentChartFactors(trialHandler.getCurrentObject());
		return null;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public List<SelectItem> getChartTypes() {
		return this.chartTypes;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setTrialHandler(final TrialHandler trialHandler) {
		this.trialHandler = trialHandler;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setService(final ChartsService service) {
		this.service = service;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getRChartType() {
		return this.rChartType;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setRChartType(final String rChartType) {
		this.rChartType = rChartType;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Map<String, String> getClickedValues() {
		return this.clickedValues;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setClickedValues(final Map<String, String> clickedValues) {
		this.clickedValues = clickedValues;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Map<String, Effect> getEffects() {
		return this.effects;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setEffects(final Map<String, Effect> effects) {
		this.effects = effects;
	}
}
