// Generated by delombok at Mon Aug 29 15:32:21 MSK 2016
package de.randi2.simulation.model;

public class SimulationRawDataEntry {
	private int run;
	private int count;
	private String treatmentArm;
	private String trialSite;
	private String stratum;

	@Override
	public String toString() {
		return run + ";" + count + ";" + treatmentArm + ";" + trialSite + ";" + stratum;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public SimulationRawDataEntry() {
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getRun() {
		return this.run;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getCount() {
		return this.count;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getTreatmentArm() {
		return this.treatmentArm;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getTrialSite() {
		return this.trialSite;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getStratum() {
		return this.stratum;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setRun(final int run) {
		this.run = run;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setCount(final int count) {
		this.count = count;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setTreatmentArm(final String treatmentArm) {
		this.treatmentArm = treatmentArm;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setTrialSite(final String trialSite) {
		this.trialSite = trialSite;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setStratum(final String stratum) {
		this.stratum = stratum;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof SimulationRawDataEntry)) return false;
		final SimulationRawDataEntry other = (SimulationRawDataEntry) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (this.getRun() != other.getRun()) return false;
		if (this.getCount() != other.getCount()) return false;
		final java.lang.Object this$treatmentArm = this.getTreatmentArm();
		final java.lang.Object other$treatmentArm = other.getTreatmentArm();
		if (this$treatmentArm == null ? other$treatmentArm != null : !this$treatmentArm.equals(other$treatmentArm)) return false;
		final java.lang.Object this$trialSite = this.getTrialSite();
		final java.lang.Object other$trialSite = other.getTrialSite();
		if (this$trialSite == null ? other$trialSite != null : !this$trialSite.equals(other$trialSite)) return false;
		final java.lang.Object this$stratum = this.getStratum();
		final java.lang.Object other$stratum = other.getStratum();
		if (this$stratum == null ? other$stratum != null : !this$stratum.equals(other$stratum)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof SimulationRawDataEntry;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + this.getRun();
		result = result * PRIME + this.getCount();
		final java.lang.Object $treatmentArm = this.getTreatmentArm();
		result = result * PRIME + ($treatmentArm == null ? 43 : $treatmentArm.hashCode());
		final java.lang.Object $trialSite = this.getTrialSite();
		result = result * PRIME + ($trialSite == null ? 43 : $trialSite.hashCode());
		final java.lang.Object $stratum = this.getStratum();
		result = result * PRIME + ($stratum == null ? 43 : $stratum.hashCode());
		return result;
	}
}
