// Generated by delombok at Mon Aug 29 15:32:21 MSK 2016
package de.randi2.jsf.wrappers;

import java.io.Serializable;
import de.randi2.model.criteria.constraints.AbstractConstraint;

public class DistributedConstraintWrapper {
	private AbstractConstraint<? extends Serializable> constraint;
	private int ratio = 0;

	public DistributedConstraintWrapper(AbstractConstraint<? extends Serializable> constraint) {
		this.constraint = constraint;
	}

	public AbstractConstraint<? extends Serializable> getConstraint() {
		return constraint;
	}

	public void setConstraint(AbstractConstraint<? extends Serializable> constraint) {
		this.constraint = constraint;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getRatio() {
		return this.ratio;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setRatio(final int ratio) {
		this.ratio = ratio;
	}
}
