// Generated by delombok at Mon Aug 29 15:32:21 MSK 2016
package de.randi2.jsf.wrappers;

import javax.faces.event.ActionEvent;
import de.randi2.jsf.controllerBeans.AbstractTrialHandler;
import de.randi2.model.TreatmentArm;

public class TreatmentArmWrapper {
	private int id = 0;
	private TreatmentArm arm;
	private final AbstractTrialHandler handler;

	public TreatmentArmWrapper(AbstractTrialHandler handler) {
		this.handler = handler;
	}

	public TreatmentArmWrapper(AbstractTrialHandler handler, TreatmentArm arm) {
		this(handler);
		this.arm = arm;
	}

	/**
	 * Action listener for removing an existing treatment arm.
	 *
	 * @param event
	 */
	public void removeArm(ActionEvent event) {
		handler.getListArmsWrapper().remove(this);
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public TreatmentArm getArm() {
		return this.arm;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public AbstractTrialHandler getHandler() {
		return this.handler;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setId(final int id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setArm(final TreatmentArm arm) {
		this.arm = arm;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "TreatmentArmWrapper(id=" + this.getId() + ", arm=" + this.getArm() + ", handler=" + this.getHandler() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof TreatmentArmWrapper)) return false;
		final TreatmentArmWrapper other = (TreatmentArmWrapper) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (this.getId() != other.getId()) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof TreatmentArmWrapper;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + this.getId();
		return result;
	}
}
