// Generated by delombok at Mon Aug 29 15:32:21 MSK 2016
package de.randi2.jsf.wrappers;

import de.randi2.model.TrialSite;

public class TrialSiteRatioWrapper {
	private TrialSite site;
	private int ratio = 1;

	public TrialSiteRatioWrapper(TrialSite site) {
		this.site = site;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public TrialSite getSite() {
		return this.site;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getRatio() {
		return this.ratio;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setSite(final TrialSite site) {
		this.site = site;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setRatio(final int ratio) {
		this.ratio = ratio;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof TrialSiteRatioWrapper)) return false;
		final TrialSiteRatioWrapper other = (TrialSiteRatioWrapper) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$site = this.getSite();
		final java.lang.Object other$site = other.getSite();
		if (this$site == null ? other$site != null : !this$site.equals(other$site)) return false;
		if (this.getRatio() != other.getRatio()) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof TrialSiteRatioWrapper;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $site = this.getSite();
		result = result * PRIME + ($site == null ? 43 : $site.hashCode());
		result = result * PRIME + this.getRatio();
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "TrialSiteRatioWrapper(site=" + this.getSite() + ", ratio=" + this.getRatio() + ")";
	}
}
