// Generated by delombok at Mon Aug 29 15:32:21 MSK 2016
/* 
 * (c) 2008- RANDI2 Core Development Team
 * 
 * This file is part of RANDI2.
 * 
 * RANDI2 is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 * 
 * RANDI2 is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * RANDI2. If not, see <http://www.gnu.org/licenses/>.
 */
package de.randi2.jsf.backingBeans;

import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import de.randi2.model.Trial;
import de.randi2.model.TrialSite;

/**
 * <p>
 * This class contains the logic for the user rights selection.
 * </p>
 *
 * @author Lukasz Plotnicki <lplotni@users.sourceforge.net>
 */
@ManagedBean(name = "rightsPanel")
@SessionScoped
public class RightsPanel {
	// Flags for the Right-Groups
	private boolean createUser = false;
	private boolean changeUser = false;
	private boolean viewUser = false;
	private boolean createTrialSite = false;
	private boolean changeTrialSite = false;
	private boolean viewTrialSite = false;
	private boolean createTrial = false;
	private boolean changeTrial = false;
	private boolean viewTrial = false;
	// ----
	// Chosen object, for which the user has some rights
	private List<TrialSite> createUserTrialSites = null;
	private List<TrialSite> viewUsers = null;
	private List<TrialSite> viewTrialSites = null;
	private List<TrialSite> createTrialCenters = null;
	private List<Trial> viewTrials = null;
	// ----
	// Flags for "chose object" logic
	private boolean createUserChosenObj = false;
	private boolean viewUsersChosenObj = false;
	private boolean viewTrialSitesChosenObj = false;
	private boolean createTrialChosenObj = false;
	private boolean viewTrialsChosenObj = false;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public RightsPanel() {
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isCreateUser() {
		return this.createUser;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isChangeUser() {
		return this.changeUser;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isViewUser() {
		return this.viewUser;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isCreateTrialSite() {
		return this.createTrialSite;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isChangeTrialSite() {
		return this.changeTrialSite;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isViewTrialSite() {
		return this.viewTrialSite;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isCreateTrial() {
		return this.createTrial;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isChangeTrial() {
		return this.changeTrial;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isViewTrial() {
		return this.viewTrial;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public List<TrialSite> getCreateUserTrialSites() {
		return this.createUserTrialSites;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public List<TrialSite> getViewUsers() {
		return this.viewUsers;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public List<TrialSite> getViewTrialSites() {
		return this.viewTrialSites;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public List<TrialSite> getCreateTrialCenters() {
		return this.createTrialCenters;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public List<Trial> getViewTrials() {
		return this.viewTrials;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isCreateUserChosenObj() {
		return this.createUserChosenObj;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isViewUsersChosenObj() {
		return this.viewUsersChosenObj;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isViewTrialSitesChosenObj() {
		return this.viewTrialSitesChosenObj;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isCreateTrialChosenObj() {
		return this.createTrialChosenObj;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isViewTrialsChosenObj() {
		return this.viewTrialsChosenObj;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setCreateUser(final boolean createUser) {
		this.createUser = createUser;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setChangeUser(final boolean changeUser) {
		this.changeUser = changeUser;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setViewUser(final boolean viewUser) {
		this.viewUser = viewUser;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setCreateTrialSite(final boolean createTrialSite) {
		this.createTrialSite = createTrialSite;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setChangeTrialSite(final boolean changeTrialSite) {
		this.changeTrialSite = changeTrialSite;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setViewTrialSite(final boolean viewTrialSite) {
		this.viewTrialSite = viewTrialSite;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setCreateTrial(final boolean createTrial) {
		this.createTrial = createTrial;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setChangeTrial(final boolean changeTrial) {
		this.changeTrial = changeTrial;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setViewTrial(final boolean viewTrial) {
		this.viewTrial = viewTrial;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setCreateUserTrialSites(final List<TrialSite> createUserTrialSites) {
		this.createUserTrialSites = createUserTrialSites;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setViewUsers(final List<TrialSite> viewUsers) {
		this.viewUsers = viewUsers;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setViewTrialSites(final List<TrialSite> viewTrialSites) {
		this.viewTrialSites = viewTrialSites;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setCreateTrialCenters(final List<TrialSite> createTrialCenters) {
		this.createTrialCenters = createTrialCenters;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setViewTrials(final List<Trial> viewTrials) {
		this.viewTrials = viewTrials;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setCreateUserChosenObj(final boolean createUserChosenObj) {
		this.createUserChosenObj = createUserChosenObj;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setViewUsersChosenObj(final boolean viewUsersChosenObj) {
		this.viewUsersChosenObj = viewUsersChosenObj;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setViewTrialSitesChosenObj(final boolean viewTrialSitesChosenObj) {
		this.viewTrialSitesChosenObj = viewTrialSitesChosenObj;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setCreateTrialChosenObj(final boolean createTrialChosenObj) {
		this.createTrialChosenObj = createTrialChosenObj;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setViewTrialsChosenObj(final boolean viewTrialsChosenObj) {
		this.viewTrialsChosenObj = viewTrialsChosenObj;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof RightsPanel)) return false;
		final RightsPanel other = (RightsPanel) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (this.isCreateUser() != other.isCreateUser()) return false;
		if (this.isChangeUser() != other.isChangeUser()) return false;
		if (this.isViewUser() != other.isViewUser()) return false;
		if (this.isCreateTrialSite() != other.isCreateTrialSite()) return false;
		if (this.isChangeTrialSite() != other.isChangeTrialSite()) return false;
		if (this.isViewTrialSite() != other.isViewTrialSite()) return false;
		if (this.isCreateTrial() != other.isCreateTrial()) return false;
		if (this.isChangeTrial() != other.isChangeTrial()) return false;
		if (this.isViewTrial() != other.isViewTrial()) return false;
		final java.lang.Object this$createUserTrialSites = this.getCreateUserTrialSites();
		final java.lang.Object other$createUserTrialSites = other.getCreateUserTrialSites();
		if (this$createUserTrialSites == null ? other$createUserTrialSites != null : !this$createUserTrialSites.equals(other$createUserTrialSites)) return false;
		final java.lang.Object this$viewUsers = this.getViewUsers();
		final java.lang.Object other$viewUsers = other.getViewUsers();
		if (this$viewUsers == null ? other$viewUsers != null : !this$viewUsers.equals(other$viewUsers)) return false;
		final java.lang.Object this$viewTrialSites = this.getViewTrialSites();
		final java.lang.Object other$viewTrialSites = other.getViewTrialSites();
		if (this$viewTrialSites == null ? other$viewTrialSites != null : !this$viewTrialSites.equals(other$viewTrialSites)) return false;
		final java.lang.Object this$createTrialCenters = this.getCreateTrialCenters();
		final java.lang.Object other$createTrialCenters = other.getCreateTrialCenters();
		if (this$createTrialCenters == null ? other$createTrialCenters != null : !this$createTrialCenters.equals(other$createTrialCenters)) return false;
		final java.lang.Object this$viewTrials = this.getViewTrials();
		final java.lang.Object other$viewTrials = other.getViewTrials();
		if (this$viewTrials == null ? other$viewTrials != null : !this$viewTrials.equals(other$viewTrials)) return false;
		if (this.isCreateUserChosenObj() != other.isCreateUserChosenObj()) return false;
		if (this.isViewUsersChosenObj() != other.isViewUsersChosenObj()) return false;
		if (this.isViewTrialSitesChosenObj() != other.isViewTrialSitesChosenObj()) return false;
		if (this.isCreateTrialChosenObj() != other.isCreateTrialChosenObj()) return false;
		if (this.isViewTrialsChosenObj() != other.isViewTrialsChosenObj()) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof RightsPanel;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + (this.isCreateUser() ? 79 : 97);
		result = result * PRIME + (this.isChangeUser() ? 79 : 97);
		result = result * PRIME + (this.isViewUser() ? 79 : 97);
		result = result * PRIME + (this.isCreateTrialSite() ? 79 : 97);
		result = result * PRIME + (this.isChangeTrialSite() ? 79 : 97);
		result = result * PRIME + (this.isViewTrialSite() ? 79 : 97);
		result = result * PRIME + (this.isCreateTrial() ? 79 : 97);
		result = result * PRIME + (this.isChangeTrial() ? 79 : 97);
		result = result * PRIME + (this.isViewTrial() ? 79 : 97);
		final java.lang.Object $createUserTrialSites = this.getCreateUserTrialSites();
		result = result * PRIME + ($createUserTrialSites == null ? 43 : $createUserTrialSites.hashCode());
		final java.lang.Object $viewUsers = this.getViewUsers();
		result = result * PRIME + ($viewUsers == null ? 43 : $viewUsers.hashCode());
		final java.lang.Object $viewTrialSites = this.getViewTrialSites();
		result = result * PRIME + ($viewTrialSites == null ? 43 : $viewTrialSites.hashCode());
		final java.lang.Object $createTrialCenters = this.getCreateTrialCenters();
		result = result * PRIME + ($createTrialCenters == null ? 43 : $createTrialCenters.hashCode());
		final java.lang.Object $viewTrials = this.getViewTrials();
		result = result * PRIME + ($viewTrials == null ? 43 : $viewTrials.hashCode());
		result = result * PRIME + (this.isCreateUserChosenObj() ? 79 : 97);
		result = result * PRIME + (this.isViewUsersChosenObj() ? 79 : 97);
		result = result * PRIME + (this.isViewTrialSitesChosenObj() ? 79 : 97);
		result = result * PRIME + (this.isCreateTrialChosenObj() ? 79 : 97);
		result = result * PRIME + (this.isViewTrialsChosenObj() ? 79 : 97);
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "RightsPanel(createUser=" + this.isCreateUser() + ", changeUser=" + this.isChangeUser() + ", viewUser=" + this.isViewUser() + ", createTrialSite=" + this.isCreateTrialSite() + ", changeTrialSite=" + this.isChangeTrialSite() + ", viewTrialSite=" + this.isViewTrialSite() + ", createTrial=" + this.isCreateTrial() + ", changeTrial=" + this.isChangeTrial() + ", viewTrial=" + this.isViewTrial() + ", createUserTrialSites=" + this.getCreateUserTrialSites() + ", viewUsers=" + this.getViewUsers() + ", viewTrialSites=" + this.getViewTrialSites() + ", createTrialCenters=" + this.getCreateTrialCenters() + ", viewTrials=" + this.getViewTrials() + ", createUserChosenObj=" + this.isCreateUserChosenObj() + ", viewUsersChosenObj=" + this.isViewUsersChosenObj() + ", viewTrialSitesChosenObj=" + this.isViewTrialSitesChosenObj() + ", createTrialChosenObj=" + this.isCreateTrialChosenObj() + ", viewTrialsChosenObj=" + this.isViewTrialsChosenObj() + ")";
	}
	// ----
}
