// Generated by delombok at Mon Aug 29 15:32:21 MSK 2016
/* 
 * (c) 2008- RANDI2 Core Development Team
 * 
 * This file is part of RANDI2.
 * 
 * RANDI2 is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 * 
 * RANDI2 is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * RANDI2. If not, see <http://www.gnu.org/licenses/>.
 */
package de.randi2.model.randomization;

import javax.persistence.Entity;
import de.randi2.randomization.BiasedCoinRandomization;
import de.randi2.randomization.RandomizationAlgorithm;

/**
 * @author jthoenes
 */
@Entity
public class BiasedCoinRandomizationConfig extends AbstractRandomizationConfig {
	private static final long serialVersionUID = -5150967612749185875L;

	public BiasedCoinRandomizationConfig(long seed) {
		super(seed);
	}

	public BiasedCoinRandomizationConfig() {
		super(null);
	}

	@Override
	public RandomizationAlgorithm<BiasedCoinRandomizationConfig> createAlgorithm() {
		return new BiasedCoinRandomization(super.getTrial());
	}

	@Override
	public RandomizationAlgorithm<? extends AbstractRandomizationConfig> createAlgorithm(long seed) {
		return new BiasedCoinRandomization(super.getTrial(), seed);
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "BiasedCoinRandomizationConfig()";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof BiasedCoinRandomizationConfig)) return false;
		final BiasedCoinRandomizationConfig other = (BiasedCoinRandomizationConfig) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof BiasedCoinRandomizationConfig;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + super.hashCode();
		return result;
	}
}
