// Generated by delombok at Mon Aug 29 15:32:21 MSK 2016
package de.randi2.model.randomization;

import java.util.Map;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.MapKeyColumn;
import de.randi2.model.AbstractDomainObject;
import de.randi2.model.TreatmentArm;

@Entity
public class MinimizationMapElementWrapper extends AbstractDomainObject {
	private static final long serialVersionUID = -2604596009904498229L;
	@ElementCollection
	@MapKeyColumn
	private Map<TreatmentArm, Double> map;

	public MinimizationMapElementWrapper() {
		// TODO Auto-generated constructor stub
	}

	public MinimizationMapElementWrapper(Map<TreatmentArm, Double> map) {
		this.map = map;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Map<TreatmentArm, Double> getMap() {
		return this.map;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setMap(final Map<TreatmentArm, Double> map) {
		this.map = map;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "MinimizationMapElementWrapper(map=" + this.getMap() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof MinimizationMapElementWrapper)) return false;
		final MinimizationMapElementWrapper other = (MinimizationMapElementWrapper) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$map = this.getMap();
		final java.lang.Object other$map = other.getMap();
		if (this$map == null ? other$map != null : !this$map.equals(other$map)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof MinimizationMapElementWrapper;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + super.hashCode();
		final java.lang.Object $map = this.getMap();
		result = result * PRIME + ($map == null ? 43 : $map.hashCode());
		return result;
	}
}
