// Generated by delombok at Mon Aug 29 15:32:21 MSK 2016
/* 
 * (c) 2008- RANDI2 Core Development Team
 * 
 * This file is part of RANDI2.
 * 
 * RANDI2 is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 * 
 * RANDI2 is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * RANDI2. If not, see <http://www.gnu.org/licenses/>.
 */
package de.randi2.model.randomization;

import javax.persistence.Entity;
import de.randi2.randomization.RandomizationAlgorithm;
import de.randi2.randomization.UrnDesign;
import de.randi2.utility.validations.randomizationConfiguration.UrnRandomizationConfigA;

@Entity
@UrnRandomizationConfigA
public class UrnDesignConfig extends AbstractRandomizationConfig {
	private static final long serialVersionUID = 8210824864257296786L;
	private int countReplacedBalls;
	private int initializeCountBalls;

	public UrnDesignConfig(long seed) {
		super(seed);
	}

	public UrnDesignConfig() {
		super(null);
	}

	@Override
	public RandomizationAlgorithm<? extends AbstractRandomizationConfig> createAlgorithm() {
		return new UrnDesign(super.getTrial());
	}

	@Override
	public RandomizationAlgorithm<? extends AbstractRandomizationConfig> createAlgorithm(long seed) {
		return new UrnDesign(super.getTrial(), seed);
	}

	@Override
	public AbstractRandomizationTempData getTempData() {
		if (tempData == null) {
			tempData = new UrnDesignTempData();
		}
		return tempData;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getCountReplacedBalls() {
		return this.countReplacedBalls;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getInitializeCountBalls() {
		return this.initializeCountBalls;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setCountReplacedBalls(final int countReplacedBalls) {
		this.countReplacedBalls = countReplacedBalls;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setInitializeCountBalls(final int initializeCountBalls) {
		this.initializeCountBalls = initializeCountBalls;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "UrnDesignConfig(countReplacedBalls=" + this.getCountReplacedBalls() + ", initializeCountBalls=" + this.getInitializeCountBalls() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof UrnDesignConfig)) return false;
		final UrnDesignConfig other = (UrnDesignConfig) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		if (this.getCountReplacedBalls() != other.getCountReplacedBalls()) return false;
		if (this.getInitializeCountBalls() != other.getInitializeCountBalls()) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof UrnDesignConfig;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + super.hashCode();
		result = result * PRIME + this.getCountReplacedBalls();
		result = result * PRIME + this.getInitializeCountBalls();
		return result;
	}
}
