// Generated by delombok at Mon Aug 29 15:32:21 MSK 2016
package de.randi2.simulation.model.helper;

public class StrataResultWrapper {
	private String strataId;
	private String strataName;
	private String algorithmName;
	private String treatmentName;
	private int minCount;
	private int maxCount;
	private double mean;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public StrataResultWrapper() {
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getStrataId() {
		return this.strataId;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getStrataName() {
		return this.strataName;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getAlgorithmName() {
		return this.algorithmName;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getTreatmentName() {
		return this.treatmentName;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getMinCount() {
		return this.minCount;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getMaxCount() {
		return this.maxCount;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public double getMean() {
		return this.mean;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setStrataId(final String strataId) {
		this.strataId = strataId;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setStrataName(final String strataName) {
		this.strataName = strataName;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setAlgorithmName(final String algorithmName) {
		this.algorithmName = algorithmName;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setTreatmentName(final String treatmentName) {
		this.treatmentName = treatmentName;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setMinCount(final int minCount) {
		this.minCount = minCount;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setMaxCount(final int maxCount) {
		this.maxCount = maxCount;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setMean(final double mean) {
		this.mean = mean;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof StrataResultWrapper)) return false;
		final StrataResultWrapper other = (StrataResultWrapper) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$strataId = this.getStrataId();
		final java.lang.Object other$strataId = other.getStrataId();
		if (this$strataId == null ? other$strataId != null : !this$strataId.equals(other$strataId)) return false;
		final java.lang.Object this$strataName = this.getStrataName();
		final java.lang.Object other$strataName = other.getStrataName();
		if (this$strataName == null ? other$strataName != null : !this$strataName.equals(other$strataName)) return false;
		final java.lang.Object this$algorithmName = this.getAlgorithmName();
		final java.lang.Object other$algorithmName = other.getAlgorithmName();
		if (this$algorithmName == null ? other$algorithmName != null : !this$algorithmName.equals(other$algorithmName)) return false;
		final java.lang.Object this$treatmentName = this.getTreatmentName();
		final java.lang.Object other$treatmentName = other.getTreatmentName();
		if (this$treatmentName == null ? other$treatmentName != null : !this$treatmentName.equals(other$treatmentName)) return false;
		if (this.getMinCount() != other.getMinCount()) return false;
		if (this.getMaxCount() != other.getMaxCount()) return false;
		if (java.lang.Double.compare(this.getMean(), other.getMean()) != 0) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof StrataResultWrapper;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $strataId = this.getStrataId();
		result = result * PRIME + ($strataId == null ? 43 : $strataId.hashCode());
		final java.lang.Object $strataName = this.getStrataName();
		result = result * PRIME + ($strataName == null ? 43 : $strataName.hashCode());
		final java.lang.Object $algorithmName = this.getAlgorithmName();
		result = result * PRIME + ($algorithmName == null ? 43 : $algorithmName.hashCode());
		final java.lang.Object $treatmentName = this.getTreatmentName();
		result = result * PRIME + ($treatmentName == null ? 43 : $treatmentName.hashCode());
		result = result * PRIME + this.getMinCount();
		result = result * PRIME + this.getMaxCount();
		final long $mean = java.lang.Double.doubleToLongBits(this.getMean());
		result = result * PRIME + (int) ($mean >>> 32 ^ $mean);
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "StrataResultWrapper(strataId=" + this.getStrataId() + ", strataName=" + this.getStrataName() + ", algorithmName=" + this.getAlgorithmName() + ", treatmentName=" + this.getTreatmentName() + ", minCount=" + this.getMinCount() + ", maxCount=" + this.getMaxCount() + ", mean=" + this.getMean() + ")";
	}
}
