// Generated by delombok at Mon Aug 29 15:32:21 MSK 2016
/* 
 * (c) 2008- RANDI2 Core Development Team
 * 
 * This file is part of RANDI2.
 * 
 * RANDI2 is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 * 
 * RANDI2 is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * RANDI2. If not, see <http://www.gnu.org/licenses/>.
 */
package de.randi2.utility;

public class StrataNameIDWrapper implements Comparable<StrataNameIDWrapper> {
	private String strataId;
	private String strataName;

	@Override
	public int compareTo(StrataNameIDWrapper o) {
		return (strataId.compareTo(o.getStrataId()));
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public StrataNameIDWrapper() {
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getStrataId() {
		return this.strataId;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getStrataName() {
		return this.strataName;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setStrataId(final String strataId) {
		this.strataId = strataId;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setStrataName(final String strataName) {
		this.strataName = strataName;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof StrataNameIDWrapper)) return false;
		final StrataNameIDWrapper other = (StrataNameIDWrapper) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$strataId = this.getStrataId();
		final java.lang.Object other$strataId = other.getStrataId();
		if (this$strataId == null ? other$strataId != null : !this$strataId.equals(other$strataId)) return false;
		final java.lang.Object this$strataName = this.getStrataName();
		final java.lang.Object other$strataName = other.getStrataName();
		if (this$strataName == null ? other$strataName != null : !this$strataName.equals(other$strataName)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof StrataNameIDWrapper;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $strataId = this.getStrataId();
		result = result * PRIME + ($strataId == null ? 43 : $strataId.hashCode());
		final java.lang.Object $strataName = this.getStrataName();
		result = result * PRIME + ($strataName == null ? 43 : $strataName.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "StrataNameIDWrapper(strataId=" + this.getStrataId() + ", strataName=" + this.getStrataName() + ")";
	}
}
